### ISSUE TITLE
img2img to tab comparison

### ISSUE THREAD

**Issue by alexbofa** [Haoming02/sd-webui-image-comparison#1]
Hello, please add the ability to transfer images from **img2img** to **tab comparison**
![00261](https://github.com/Haoming02/sd-webui-image-comparison/assets/58225118/2bcd12f2-a2da-4fdf-8dce-dbc7765b0484)
And the ability to enlarge the picture either with a paw or zoom in another way, sometimes it is difficult to view the details.

**Comment by Haoming02** [comment]
~~Only 2 months later~~

**Comment by alexbofa** [comment]
Thanks! ❤️

![image](https://github.com/Haoming02/sd-webui-image-comparison/assets/58225118/13532fe8-c328-46f1-8510-7c74043779ff)
And this button is from this extension?
https://github.com/Haoming02/sd-webui-image-comparison/issues/3#issuecomment-2016505807
