### ISSUE TITLE
txt2img compatability?

### ISSUE THREAD

**Issue by Terroosh** [Haoming02/sd-webui-image-comparison#3]
Is this something that could be added to the txt2img? As in take the previous generation from txt2img and the newest txt2img generation and send them to comparison. I always felt like the webui needed something this.

**Comment by Haoming02** [comment]
Please test it out~

Whenever you click **Generate**, it would try to cache the image currently shown in the result; then when you click `Send to Comparison`, it would load the cached image as well as the current result for comparison.

**Comment by Terroosh** [comment]
> Please test it out~
> 
> Whenever you click **Generate**, it would try to cache the image currently shown in the result; then when you click `Send to Comparison`, it would load the cached image as well as the current result for comparison.

That's amazing, works great. Thanks!
